name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0

permissions:
  id-token: write  # Needed for trusted publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build tools
      run: |
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
